[package]
name = "p3-server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3"
wasi = { git = "https://github.com/rvolosatovs/wasi", branch = "feat/p3" }
